<?php 
	include_once("index.html");
	include_once("img/AlphaTauri.png");
	include_once("img/AstonMartin.png");
	include_once("img/Alpine.png");
	include_once("img/FERRARI.png");
	include_once("img/McLaren.png");
	include_once("img/Mercedes.png");
	include_once("img/RedBull.png");
 ?>